$wallust_bgo = {{ background | strip }}
$wallust_fg = {{ foreground | strip }}
$wallust_color0 = {{ color0 | strip }}
$wallust_color1 = {{ color1 | strip }}
$wallust_color2 = {{ color2 | strip }}
$wallust_color3 = {{ color3 | strip }}
$wallust_color4 = {{ color4 | strip }}
$wallust_color5 = {{ color5 | strip }}
$wallust_color6 = {{ color6 | strip }}
$wallust_color7 = {{ color7 | strip }}
$wallust_color8 = {{ color8 | strip }}
$wallust_color9 = {{ color9 | strip }}
$wallust_color10 = {{ color10 | strip }}
$wallust_color11 = {{ color11 | strip }}
$wallust_color12 = {{ color12 | strip }}
$wallust_color13 = {{ color13 | strip }}
$wallust_color14 = {{ color14 | strip }}
$wallust_color15 = {{ color15 | strip }}